<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: chris
 * Date: Mon, 25 Apr 2016 22:38:58 -0300
 */

$conf['title'] = 'SurDev_wiki';
$conf['lang'] = 'es';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
